# Generated by Django 5.0.14 on 2026-08-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresados', '0006_evento_imagen'),
        ('usuarios', '0003_rename_rol_coordinador_egresados'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='egresados.programa'),
        ),
    ]
